# Generated by Django 5.1.15 on 2026-07-03 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Ключ (для фильтра)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория проекта',
                'verbose_name_plural': 'Категории проектов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('lead', models.TextField(verbose_name='Краткое описание')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('recruiting', 'Идёт набор'), ('archived', 'Архив')], default='active', max_length=20, verbose_name='Статус')),
                ('stat_1_num', models.CharField(blank=True, max_length=30, verbose_name='Показатель 1: значение')),
                ('stat_1_label', models.CharField(blank=True, max_length=60, verbose_name='Показатель 1: подпись')),
                ('stat_2_num', models.CharField(blank=True, max_length=30, verbose_name='Показатель 2: значение')),
                ('stat_2_label', models.CharField(blank=True, max_length=60, verbose_name='Показатель 2: подпись')),
                ('stat_3_num', models.CharField(blank=True, max_length=30, verbose_name='Показатель 3: значение')),
                ('stat_3_label', models.CharField(blank=True, max_length=60, verbose_name='Показатель 3: подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', 'id'],
            },
        ),
    ]
