# Generated by Django 5.1.15 on 2026-07-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.CharField(max_length=64, unique=True, verbose_name='ID в ВК')),
                ('title', models.CharField(blank=True, help_text='Автоматически берётся из первой строки текста.', max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст поста')),
                ('image', models.URLField(blank=True, help_text='Первая картинка из вложений поста.', max_length=500, verbose_name='URL картинки')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка на пост в ВК')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайков')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='Комментариев')),
                ('is_visible', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть пост, не удаляя его.', verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Пост ВК',
                'verbose_name_plural': 'Лента ВК',
                'ordering': ['-published_at'],
            },
        ),
    ]
