# Generated by Django 5.1.15 on 2026-07-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Например: «1 200+», «86», «7 лет».', max_length=20, verbose_name='Значение')),
                ('label', models.CharField(max_length=100, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Показатель на баннере',
                'verbose_name_plural': 'Показатели на баннере',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Используется для подсветки активного пункта. Значения: home, team, news, projects, contacts.', max_length=60, unique=True, verbose_name='Ключ страницы')),
                ('url', models.CharField(help_text='Может быть якорем (#news), внутренним путём (/team/) или внешней ссылкой.', max_length=500, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Отображается в шапке и во вкладке браузера. Формат SVG или PNG с прозрачным фоном.', null=True, upload_to='settings/', verbose_name='Логотип')),
                ('banner', models.ImageField(blank=True, help_text='Крупное изображение для главной. Рекомендуемый размер — от 1600 × 900 px.', null=True, upload_to='settings/', verbose_name='Фон hero-баннера')),
                ('hero_eyebrow', models.CharField(blank=True, default='Набор открыт — присоединяйтесь', help_text='Короткая метка над основным заголовком. Оставьте пустой, чтобы скрыть.', max_length=120, verbose_name='Плашка над заголовком')),
                ('hero_title', models.CharField(default='Помогаем людям, делаем город', max_length=200, verbose_name='Заголовок баннера')),
                ('hero_title_accent', models.CharField(blank=True, default='лучше', help_text='Показывается на новой строке с зелёным подчёркиванием.', max_length=80, verbose_name='Выделенное слово в заголовке')),
                ('hero_lead', models.TextField(blank=True, help_text='Текст под заголовком, 1–3 предложения.', verbose_name='Подзаголовок баннера')),
                ('hero_primary_text', models.CharField(default='Присоединиться', max_length=60, verbose_name='Текст основной кнопки')),
                ('hero_secondary_text', models.CharField(blank=True, default='Узнать больше', help_text='Оставьте пустой, чтобы скрыть вторую кнопку.', max_length=60, verbose_name='Текст второй кнопки')),
                ('hero_secondary_url', models.CharField(blank=True, default='#about', max_length=500, verbose_name='Ссылка второй кнопки')),
                ('cta_title', models.CharField(default='Присоединяйтесь к команде волонтёров', max_length=200, verbose_name='Заголовок CTA-блока')),
                ('cta_lead', models.TextField(blank=True, default='Заполните короткую анкету — мы свяжемся с вами и подберём направление, которое подходит именно вам.', verbose_name='Текст CTA-блока')),
                ('cta_button_text', models.CharField(default='Заполнить анкету', max_length=60, verbose_name='Текст кнопки CTA')),
                ('join_url', models.URLField(blank=True, help_text='Куда ведут все кнопки CTA. Обычно — Яндекс.Форма или Google Form.', max_length=500, verbose_name='Ссылка «Стать волонтёром»')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Формат для показа: +7 (000) 000-00-00.', max_length=40, verbose_name='Телефон')),
                ('phone_hint', models.CharField(blank=True, default='пн–пт, 10:00–18:00', max_length=100, verbose_name='Подсказка к телефону')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('address_hint', models.CharField(blank=True, help_text='Например, «2 этаж, вход со двора».', max_length=200, verbose_name='Подсказка к адресу')),
                ('vk_url', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('map_embed', models.TextField(blank=True, help_text='Iframe с Яндекс.Карт (получить: «Поделиться» → «Код для сайта»).', verbose_name='HTML-код карты')),
                ('vk_group_id', models.CharField(blank=True, help_text='Только цифры — например, для vk.com/club12345 введите 12345.', max_length=64, verbose_name='ID группы ВКонтакте')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
