# Generated by Django 5.1.15 on 2026-07-03 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Группа команды',
                'verbose_name_plural': 'Группы команды',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, help_text='Соотношение 3:4, минимум 400 × 533 px.', null=True, upload_to='team/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в группе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='team.teamgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Член ИРВЦ',
                'verbose_name_plural': 'Состав ИРВЦ',
                'ordering': ['group__order', 'order', 'id'],
            },
        ),
    ]
